package paneles.buscar;

import paneles.buscar.tipos.tipoCancha;
import paneles.buscar.tipos.tipoCliente;
import paneles.buscar.tipos.tipoFactura;

public class pnlBuscar extends javax.swing.JPanel {
    
    tipoCancha pnlCancha = new tipoCancha();
    tipoCliente pnlCliente = new tipoCliente();
    tipoFactura pnlFactura = new tipoFactura();

    public pnlBuscar() {
        initComponents();
        pnlContenedor.add(pnlCliente);
        pnlContenedor.add(pnlCancha);
        pnlContenedor.add(pnlFactura);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBuscarCombo = new javax.swing.JPanel();
        cbBuscar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jpBuscarCombo.setBackground(new java.awt.Color(255, 255, 255));

        cbBuscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        cbBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clientes", "Canchas", "Facturación" }));
        cbBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbBuscarMouseClicked(evt);
            }
        });
        cbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Buscar por:");

        javax.swing.GroupLayout jpBuscarComboLayout = new javax.swing.GroupLayout(jpBuscarCombo);
        jpBuscarCombo.setLayout(jpBuscarComboLayout);
        jpBuscarComboLayout.setHorizontalGroup(
            jpBuscarComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscarComboLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jpBuscarComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBuscarComboLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52)))
                .addGap(49, 49, 49))
        );
        jpBuscarComboLayout.setVerticalGroup(
            jpBuscarComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBuscarComboLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedor.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpBuscarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBuscarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBuscarActionPerformed
        int index = cbBuscar.getSelectedIndex();
        //JOptionPane.showMessageDialog(pnlCliente, "hsasdhagh");
        if(index == 0){
           pnlContenedor.add(pnlCliente);
           pnlContenedor.add(pnlCancha);
           pnlContenedor.add(pnlFactura);
        } 
        if(index == 1){
            pnlContenedor.add(pnlCancha);
            pnlContenedor.add(pnlCliente);
            pnlContenedor.add(pnlFactura);
        }
         if(index == 2){
            pnlContenedor.add(pnlFactura);
            pnlContenedor.add(pnlCancha);
            pnlContenedor.add(pnlCliente);
        }
    }//GEN-LAST:event_cbBuscarActionPerformed

    private void cbBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbBuscarMouseClicked
           // TODO add your handling code here:
    }//GEN-LAST:event_cbBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpBuscarCombo;
    private javax.swing.JPanel pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
